Repository projectcalico/typha, pull requests merged in 2019-10, with the labels that each got.

#315 need to harden go mod downloads against network errors
  Makefile
Labels: docs-not-required, release-note-not-required

#320 README: fix subtest title typo
  README.md
Labels: docs-pr-required, release-note-required

#318 Update libcalico pin
  go.mod
  go.sum
  pkg/logutils/logutils.go
Labels: docs-not-required, release-note-not-required

#319 [release-v3.10] Automatic update of libcalico-go to 399044ecb65942961586f38c38415d95b9122dcc
  go.mod
  go.sum
  pkg/logutils/logutils.go
Labels: docs-not-required, release-note-not-required

#321 Use client-go v12.0.0
  check-licenses/check_licenses.go
  glide.lock
  glide.yaml
  pkg/logutils/logutils.go
Labels: docs-not-required, release-note-required

#322 Token projection support
  go.mod
  go.sum
  pkg/logutils/logutils.go
Labels: docs-not-required, release-note-required

#323 Remove 'undo' behavior from local_build
  Makefile
Labels: docs-not-required, release-note-not-required
