Repository projectcalico/typha, pull requests merged in 2019-04, with the labels that each got.

#259 Update libcalico-go
  fv-tests/server_test.go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#260 glide: update libcalico-go to have new Felix config params
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#261 [master] Automatic update of libcalico-go to 727a39e77d674af6e7d6684b941916183d80f5de
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#262 [master] Automatic update of libcalico-go to 419f1c6419fc7f07ba2dfc536a12e30d69886294
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#263 Use calico fork of logrus
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#264 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#265 Update of libcalico-go to pull in host-local changes
  Makefile
  glide.lock
  glide.yaml
  pkg/daemon/daemon.go
Labels: docs-not-reqiured, release-note-not-required

#267 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#269 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#270 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
