Repository projectcalico/typha, pull requests merged in 2020-11, with the labels that each got.

#444 [master] Automatic update of sempahore YAMLs.
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#446 Fix release branch pin update regex (add ^ to start)
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#445 Update libcalico-go pin
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#448 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#450 Trigger confd pin update (instead of libcalico-go)
  Makefile
Labels: docs-not-required, release-note-not-required

#451 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#453 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#449 Fix v3 resource deduplication.
  fv-tests/server_test.go
  pkg/snapcache/cache_test.go
  pkg/syncproto/sync_proto.go
Labels: cherry-pick-candidate, docs-pr-required, merge-when-ready, release-note-required

#454 [v3.17] Backport v3 resource deduplication fix
  fv-tests/server_test.go
  pkg/snapcache/cache_test.go
  pkg/syncproto/sync_proto.go
Labels: docs-not-required, release-note-required

#455 [v3.16] Backport v3 resource deduplication fix
  fv-tests/server_test.go
  pkg/snapcache/cache_test.go
  pkg/syncproto/sync_proto.go
Labels: docs-not-required, merge-when-ready, release-note-required

#456 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#457 Increase minimum TLS version to v1.2 for improved security.
  fv-tests/server_test.go
  pkg/config/file_loader_test.go
  pkg/snapcache/cache_test.go
  pkg/syncclient/sync_client.go
  pkg/syncserver/sync_server.go
Labels: docs-not-required, release-note-required

#460 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#461 update pins
  go.mod
  go.sum
  pkg/k8s/lookup.go
  pkg/syncclientutils/startsyncerclient.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required, squash-commits
