Repository projectcalico/typha, pull requests merged in 2020-01, with the labels that each got.

#341 release-v3.8 - Update libcalico-go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#340 release-v3.9 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, release-note-required

#339 release-v3.10 - Update libcalico-go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#342 Only require go 1.12 for now
  go.mod
Labels: docs-not-required, release-note-not-required

#344 Update libcalico pin for rule metadata
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#343 Add nsswitch.conf to docker image
  docker-image/Dockerfile.amd64
  docker-image/nsswitch.conf
Labels: docs-not-required, release-note-required

#346 Ensure appending to PUSH_IMAGES is not part of a recipe
  Makefile
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#347 Cherry-pick Ensure appending to PUSH_IMAGES is not part of a recipe (#346)
  Makefile
Labels: docs-not-required, release-note-not-required

#348 Typha connections limit needs to account for confd
  pkg/config/config_params.go
  pkg/k8s/rebalance.go
  pkg/k8s/rebalance_test.go
Labels: docs-not-required, release-note-not-required
