Repository projectcalico/typha, pull requests merged in 2020-10, with the labels that each got.

#427 Semaphore Auto Pin Update PR
  go.mod
  go.sum
  pkg/config/env_var_loader_test.go
  pkg/config/file_loader_test.go
  pkg/config/param_types_test.go
Labels: docs-not-required, release-note-not-required

#428 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#429 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#430 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#431 Update pins (for BGP password support)
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#432 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#434 Update go-build version to v0.48 (go 1.15.2)
  Makefile
  go.mod
  go.sum
  pkg/syncclient/sync_client.go
Labels: docs-pr-required, release-note-required

#435 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#436 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#437 Rework so that gomega is always a dot import
  pkg/config/config_params_test.go
  pkg/config/env_var_loader_test.go
  pkg/config/file_loader_test.go
  pkg/config/param_types_test.go
Labels: docs-not-required, release-note-not-required

#440 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#441 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#442 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
