Repository projectcalico/typha, pull requests merged in 2020-09, with the labels that each got.

#397 Pick up felixconfiguration updates
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#398 [release-v3.16] Pick up felixconfiguration updates
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#399 [release-v3.15] Pick up felixconfiguration updates
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#400 Respect new libcalico-go datastore type defaulting behaviour.
  pkg/config/config_params.go
Labels: docs-not-required, release-note-not-required

#401 Rev pins
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#403 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-pr-required, merge-when-ready, release-note-required

#406 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-pr-required, merge-when-ready, release-note-required

#407 Rev libcalico-go and remove datastore defaulting.
  go.mod
  go.sum
  pkg/config/config_params.go
Labels: docs-not-required, release-note-not-required

#409 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#405 Add update_pins pipeline to trigger pin updates
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
Labels: docs-pr-required, release-note-required

#410 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#412 Delete common makefiles on clean
  Makefile
Labels: docs-pr-required, release-note-required

#415 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#417 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#416 Trigger felix pin update on merge to master or release branches
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#421 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: docs-not-required, merge-when-ready, release-note-not-required

#422 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required

#426 gomega.Default conflicts with config.Default
  pkg/config/config_params_test.go
Labels: docs-pr-required, release-note-required
