Repository projectcalico/typha, pull requests merged in 2020-08, with the labels that each got.

#387 Remove vendor dir if it exists on clean
  Makefile
Labels: docs-not-required, release-note-required

#389 Migrate to Semaphore v2
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#390 Tidy update semaphore v2 build, fix caching issue
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#391 Use unique cache key and add clear cache promotion
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#392 Rev libcalico-go to pick up BPF fixes.
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#393 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#394 Log out Kubernetes connection parameters for easier debugging.
  pkg/daemon/daemon.go
Labels: docs-not-required, release-note-not-required

#395 V3.16 log out k8s params
  pkg/daemon/daemon.go
Labels: docs-pr-required, release-note-required

#396 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
