Repository projectcalico/typha, pull requests merged in 2020-12, with the labels that each got.

#462 Move typha endpoint discovery to this repo so it can be shared
  .gitignore
  go.mod
  pkg/discovery/discovery.go
  pkg/discovery/discovery_suite_test.go
  pkg/discovery/discovery_test.go
Labels: docs-not-required, release-note-required

#463 Coalesce multiple versions of the discovery logic.
  pkg/discovery/discovery.go
  pkg/syncclientutils/startsyncerclient.go
Labels: docs-not-required, release-note-not-required

#464 Fix name of discovery flag.
  pkg/discovery/discovery.go
Labels: docs-not-required, release-note-not-required

#466 [v3.17] Backport: Move kubernetes discovery to Typha so it can be shared.
  .gitignore
  go.mod
  pkg/discovery/discovery.go
  pkg/discovery/discovery_suite_test.go
  pkg/discovery/discovery_test.go
  pkg/syncclientutils/startsyncerclient.go
Labels: docs-pr-required, release-note-required

#467 [v3.16] Backport Semaphore v2 builds
  .semaphore/clear_cache.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-not-required, release-note-not-required

#465 [v3.16] Backport: Move kubernetes discovery to Typha so it can be shared.
  .gitignore
  go.mod
  pkg/discovery/discovery.go
  pkg/discovery/discovery_suite_test.go
  pkg/discovery/discovery_test.go
  pkg/syncclientutils/startsyncerclient.go
Labels: docs-not-required, release-note-required

#468 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#469 Automated cherry pick of #468: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#470 Automated cherry pick of #468: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-pr-required, release-note-required

#471 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#472 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#473 Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#474 Automated cherry pick of #473: Fix make cd target to use correct tag for docker images
  Makefile
Labels: docs-not-required, release-note-not-required

#475 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#476 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#477 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
