Repository projectcalico/typha, pull requests merged in 2021-06, with the labels that each got.

#581 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#582 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#584 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#585 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#583 Replace lib/v3 package with projectcalico/api
  fv-tests/server_test.go
  go.mod
  go.sum
  pkg/calc/calc_test.go
  pkg/snapcache/cache_test.go
Labels: docs-pr-required, release-note-required

#587 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-pr-required, release-note-required

#588 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#589 Update api pins on pin update
  Makefile
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#591 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#592 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#593 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
