Repository projectcalico/typha, pull requests merged in 2021-08, with the labels that each got.

#631 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#630 [release-v3.18] Semaphore Auto Pin Update
  .semaphore/semaphore.yml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch, squash-commits

#638 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#640 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#641 Change release repo to docker.io, add RELEASE and CONFIRM env variables
  Makefile
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#643 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#642 Automated cherry pick of #641: Change release repo to docker.io, add RELEASE and CONFIRM env
  Makefile
Labels: docs-not-required, release-note-not-required

#644 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#645 Clear up space for semaphore builds
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#646 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#647 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#648 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#649 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#650 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#651 Unmount the pre-loaded image cache for semaphore
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
