Repository projectcalico/typha, pull requests merged in 2021-11, with the labels that each got.

#690 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#691 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#692 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#693 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#694 Restrict Typha server to FIPS compliant cipher suites
  pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required

#696 Automated cherry pick of #694: Restrict Typha server to FIPS compliant cipher suites
  pkg/syncserver/sync_server.go
Labels: release-note-required, docs-not-required

#697 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#698 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#700 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#701 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#703 [release-v3.18] Semaphore Auto Pin Update
  .semaphore/semaphore.yml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#702 [release-v3.19] Semaphore Auto Pin Update
  .semaphore/semaphore.yml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#704 [v3.20] Pick Merge pull request #651 from Brian-McM/bm-free-up-container-space-in-…
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required
